[package]
name = "football-api"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "1.0.56"
axum = "0.4.8"
hyper = { version = "0.14", features = ["full"] }
hyper-tls = "0.5.0"
reqwest = "0.11.10"
serde_json = "1.0.79"
tokio = { version = "1.17", features = ["full"] }
